name: Face Assist
version: 1.0.0
slug: face_assist
description: AI-powered face detection and recognition add-on with user-friendly web interface
url: https://github.com/nathanmtl/face-assist-addon
arch:
  - aarch64
startup: application
boot: auto
init: false
hassio_api: true
hassio_role: default
homeassistant_api: true
ingress: true
ingress_port: 8099
panel_icon: mdi:face-recognition
panel_title: Face Assist
host_network: false
privileged:
  - SYS_ADMIN  # For Hailo device access
devices:
  - /dev/hailo0
map:
  - share:rw
  - ssl
webui: http://[HOST]:[PORT:8099]
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface (Not required for Home Assistant Ingress)
stage: stable
options:
  models_path: /share/face-assist/models
  faces_path: /share/face-assist/faces
  results_path: /share/face-assist/results
  max_model_size: 500
  log_level: info
schema:
  models_path: str
  faces_path: str
  results_path: str
  max_model_size: int
  log_level: list(trace|debug|info|notice|warning|error|fatal)
